apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: demonamespace
spec:
  serviceAccountName: fortanix-csi-provider
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
	env:  
    - name: ARGOCD_SECRET
      valueFrom:  
      secretKeyRef:  
        name: ARGOCD_SECRET    # Reference the created Kubernetes secret  
        key: argocdsecret01    # Reference the key in the secre
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "fortanix-test"

